name: Log Time Job

on:
  push:
    branches:
      - main

jobs:
  update-log:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update log file with new timestamp
      run: echo "$(date)" >> log.txt

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add log.txt
        git commit -m "Update log file with new timestamp"
        git push
      env:
        GITHUB_TOKEN: ${{ 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 }}
